// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/version/v1/version.proto

package version

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type VersionResponse struct {
	Version        string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Checksum       []byte `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	LastCommitSHA  string `protobuf:"bytes,3,opt,name=lastCommitSHA,proto3" json:"lastCommitSHA"`
	LastCommitTime string `protobuf:"bytes,4,opt,name=lastCommitTime,proto3" json:"lastCommitTime,omitempty"`
	BuildTime      string `protobuf:"bytes,5,opt,name=buildTime,proto3" json:"buildTime,omitempty"`
	GitBranch      string `protobuf:"bytes,6,opt,name=gitBranch,proto3" json:"gitBranch,omitempty"`
	GoVersion      string `protobuf:"bytes,7,opt,name=goVersion,proto3" json:"goVersion,omitempty"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e0ee4c921f1b0fa, []int{0}
}
func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return m.Size()
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *VersionResponse) GetChecksum() []byte {
	if m != nil {
		return m.Checksum
	}
	return nil
}

func (m *VersionResponse) GetLastCommitSHA() string {
	if m != nil {
		return m.LastCommitSHA
	}
	return ""
}

func (m *VersionResponse) GetLastCommitTime() string {
	if m != nil {
		return m.LastCommitTime
	}
	return ""
}

func (m *VersionResponse) GetBuildTime() string {
	if m != nil {
		return m.BuildTime
	}
	return ""
}

func (m *VersionResponse) GetGitBranch() string {
	if m != nil {
		return m.GitBranch
	}
	return ""
}

func (m *VersionResponse) GetGoVersion() string {
	if m != nil {
		return m.GoVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "jwtis.services.version.v1.VersionResponse")
}

func init() { proto.RegisterFile("api/version/v1/version.proto", fileDescriptor_4e0ee4c921f1b0fa) }

var fileDescriptor_4e0ee4c921f1b0fa = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcf, 0x4e, 0xc2, 0x30,
	0x18, 0x67, 0xa8, 0x20, 0x8d, 0x68, 0xb2, 0x83, 0xa9, 0x93, 0x0c, 0xc2, 0xc1, 0x10, 0x13, 0x5b,
	0x40, 0x6f, 0x9e, 0xc4, 0x98, 0x70, 0x50, 0x0f, 0xd3, 0x18, 0xe3, 0x6d, 0x9b, 0x75, 0x54, 0xd8,
	0xba, 0xac, 0xdd, 0x8c, 0x6f, 0x61, 0xe2, 0x4b, 0x79, 0xe4, 0xe8, 0x89, 0x98, 0x71, 0xf3, 0x29,
	0xcc, 0xba, 0x8d, 0x01, 0x89, 0xb7, 0xdf, 0xbf, 0x76, 0xdf, 0x7e, 0x5f, 0x41, 0xc3, 0xf4, 0x29,
	0x8e, 0x48, 0xc0, 0x29, 0xf3, 0x70, 0xd4, 0xcb, 0x21, 0xf2, 0x03, 0x26, 0x98, 0x7a, 0xf0, 0xfa,
	0x26, 0x28, 0x47, 0x9c, 0x04, 0x11, 0xb5, 0x09, 0x47, 0xb9, 0x1b, 0xf5, 0xb4, 0x43, 0x87, 0x31,
	0x67, 0x42, 0xb0, 0x0c, 0x5a, 0xe1, 0x0b, 0x26, 0xae, 0x2f, 0xde, 0xd3, 0x73, 0xda, 0x89, 0x43,
	0xc5, 0x28, 0xb4, 0x90, 0xcd, 0x5c, 0xec, 0x30, 0x87, 0x15, 0xa9, 0x84, 0x49, 0x22, 0x51, 0x1a,
	0x6f, 0x7f, 0x96, 0xc1, 0xde, 0x43, 0x7a, 0xb5, 0x41, 0xb8, 0xcf, 0x3c, 0x4e, 0x54, 0x08, 0xaa,
	0xd9, 0xd7, 0xa0, 0xd2, 0x52, 0x3a, 0x35, 0x23, 0xa7, 0xaa, 0x06, 0xb6, 0xed, 0x11, 0xb1, 0xc7,
	0x3c, 0x74, 0x61, 0xb9, 0xa5, 0x74, 0x76, 0x8c, 0x05, 0x57, 0x87, 0xa0, 0x3e, 0x31, 0xb9, 0xb8,
	0x64, 0xae, 0x4b, 0xc5, 0xdd, 0xf0, 0x02, 0x6e, 0x24, 0x67, 0x07, 0xed, 0x78, 0xd6, 0xac, 0x5f,
	0x2f, 0x1b, 0xbf, 0xb3, 0xe6, 0x6a, 0xd2, 0x58, 0xa5, 0xea, 0x11, 0xd8, 0x2d, 0x84, 0x7b, 0xea,
	0x12, 0xb8, 0x29, 0xc7, 0x58, 0x53, 0xd5, 0x06, 0xa8, 0x59, 0x21, 0x9d, 0x3c, 0xcb, 0xc8, 0x96,
	0x8c, 0x14, 0x42, 0xe2, 0x3a, 0x54, 0x0c, 0x02, 0xd3, 0xb3, 0x47, 0xb0, 0x92, 0xba, 0x0b, 0x41,
	0xba, 0x2c, 0xfb, 0x71, 0x58, 0xcd, 0xdc, 0x5c, 0xe8, 0x3f, 0x82, 0x6a, 0x06, 0xd5, 0x9b, 0x02,
	0xee, 0xa3, 0xb4, 0x78, 0x94, 0x57, 0x8a, 0xae, 0x92, 0xe2, 0xb5, 0x63, 0xf4, 0xef, 0xae, 0xd0,
	0x5a, 0xb7, 0x83, 0xdb, 0xaf, 0x58, 0x57, 0xa6, 0xb1, 0xae, 0xfc, 0xc4, 0xba, 0xf2, 0x31, 0xd7,
	0x4b, 0xd3, 0xb9, 0x5e, 0xfa, 0x9e, 0xeb, 0xa5, 0xa7, 0xb3, 0xa5, 0xc5, 0x8d, 0xcd, 0xc0, 0xf4,
	0x04, 0xf5, 0xfa, 0xdd, 0x7e, 0x17, 0xcb, 0xcb, 0xf1, 0xea, 0x63, 0x39, 0xcf, 0xa0, 0x55, 0x91,
	0xb3, 0x9c, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x13, 0x17, 0x9c, 0x4d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VersionClient is the client API for Version service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VersionClient interface {
	Version(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type versionClient struct {
	cc *grpc.ClientConn
}

func NewVersionClient(cc *grpc.ClientConn) VersionClient {
	return &versionClient{cc}
}

func (c *versionClient) Version(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/jwtis.services.version.v1.Version/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VersionServer is the server API for Version service.
type VersionServer interface {
	Version(context.Context, *empty.Empty) (*VersionResponse, error)
}

// UnimplementedVersionServer can be embedded to have forward compatible implementations.
type UnimplementedVersionServer struct {
}

func (*UnimplementedVersionServer) Version(ctx context.Context, req *empty.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}

func RegisterVersionServer(s *grpc.Server, srv VersionServer) {
	s.RegisterService(&_Version_serviceDesc, srv)
}

func _Version_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jwtis.services.version.v1.Version/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionServer).Version(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Version_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jwtis.services.version.v1.Version",
	HandlerType: (*VersionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Version_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/version/v1/version.proto",
}

func (m *VersionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VersionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VersionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GoVersion) > 0 {
		i -= len(m.GoVersion)
		copy(dAtA[i:], m.GoVersion)
		i = encodeVarintVersion(dAtA, i, uint64(len(m.GoVersion)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.GitBranch) > 0 {
		i -= len(m.GitBranch)
		copy(dAtA[i:], m.GitBranch)
		i = encodeVarintVersion(dAtA, i, uint64(len(m.GitBranch)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.BuildTime) > 0 {
		i -= len(m.BuildTime)
		copy(dAtA[i:], m.BuildTime)
		i = encodeVarintVersion(dAtA, i, uint64(len(m.BuildTime)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.LastCommitTime) > 0 {
		i -= len(m.LastCommitTime)
		copy(dAtA[i:], m.LastCommitTime)
		i = encodeVarintVersion(dAtA, i, uint64(len(m.LastCommitTime)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.LastCommitSHA) > 0 {
		i -= len(m.LastCommitSHA)
		copy(dAtA[i:], m.LastCommitSHA)
		i = encodeVarintVersion(dAtA, i, uint64(len(m.LastCommitSHA)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Checksum) > 0 {
		i -= len(m.Checksum)
		copy(dAtA[i:], m.Checksum)
		i = encodeVarintVersion(dAtA, i, uint64(len(m.Checksum)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintVersion(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVersion(dAtA []byte, offset int, v uint64) int {
	offset -= sovVersion(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VersionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovVersion(uint64(l))
	}
	l = len(m.Checksum)
	if l > 0 {
		n += 1 + l + sovVersion(uint64(l))
	}
	l = len(m.LastCommitSHA)
	if l > 0 {
		n += 1 + l + sovVersion(uint64(l))
	}
	l = len(m.LastCommitTime)
	if l > 0 {
		n += 1 + l + sovVersion(uint64(l))
	}
	l = len(m.BuildTime)
	if l > 0 {
		n += 1 + l + sovVersion(uint64(l))
	}
	l = len(m.GitBranch)
	if l > 0 {
		n += 1 + l + sovVersion(uint64(l))
	}
	l = len(m.GoVersion)
	if l > 0 {
		n += 1 + l + sovVersion(uint64(l))
	}
	return n
}

func sovVersion(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVersion(x uint64) (n int) {
	return sovVersion(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VersionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVersion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VersionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VersionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checksum", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVersion
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVersion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Checksum = append(m.Checksum[:0], dAtA[iNdEx:postIndex]...)
			if m.Checksum == nil {
				m.Checksum = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCommitSHA", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastCommitSHA = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCommitTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastCommitTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuildTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuildTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GitBranch", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GitBranch = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVersion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVersion
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVersion
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVersion(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthVersion
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthVersion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVersion(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVersion
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVersion
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVersion
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVersion
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVersion
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVersion
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVersion        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVersion          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVersion = fmt.Errorf("proto: unexpected end of group")
)
